/*
-------------------------------------------------------What is Machine Code?---------------------------------------------------------------

1. Machine code is a binary code which an Operating System can Understand.
2. Machine code is a set of instructions executed directly by a computer's central processing unit (CPU).
3. Machine code is written in binary, using only the numbers 0 and 1.
4. Machine code is the lowest level of programming language and is specific to a particular computer architecture.
5. Machine code is the only language a computer understands, as it is the language of the CPU.
6. Machine code is generated by compilers and assemblers when source code is translated into machine code.
7. Machine code is difficult for humans to read and write, as it is not designed for human comprehension.
8. Machine code is the most basic form of programming language and is used to create software and applications.

Machine Code Kya Hai?
Machine Code ek computer ki language hai jo sirf 0 aur 1 (binary numbers) me hoti hai.
Ye wahi instructions hain jo CPU (computer ka brain) directly samajh sakta hai aur execute kar sakta hai.

Example:Suppose hum computer se kehna chahte hain ki "2 aur 3 ko add karo" Machine code me ye instruction kuch is tarah hoga:
1011 0001 0010 0011
Yaha, binary numbers CPU ko batate hain ki kya karna hai (Add operation) aur kin numbers par kaam karna hai (2 aur 3).

Machine code ko generate karne ke liye hum compilers aur assemblers ka use karte hain, jo source code ko machine code me translate karte hain.


-----------------------------------------------------Features of Machine Code------------------------------------------------------------------

1. Binary Format:
Ye sirf 0 aur 1 me hota hai, kyunki computer hardware sirf binary signals samajhta hai.

2. Directly Understood by CPU:
Machine code kisi translation ki zarurat ke bina computer ke processor ko samajh aata hai.

3. Difficult for Humans:
Humans ke liye machine code samajhna mushkil hai, isliye hum high-level languages (jaise Python ya Java) ka use karte hain.
C/C++ jaise languages ko hum bolne wale languages kehte hain, jo machine code me convert hoti hain.
C/C++ code ko compile karne se machine code generate hoti hai, jo computer samajh sakta hai.
C/c++ are Middle Level languages.


-----------------------------------------------------Simple Analogy (Asaan Example)---------------------------------------------------------

Machine Code ko ek light switch ke tarah samjho:
0 = Switch off (koi action nahi).
1 = Switch on (action execute ho raha hai).
Machine code ka combination CPU ko batata hai ki kya action karna hai.


---------------------------------------------------------Importance Of Machine Code---------------------------------------------------------------

1. Machine code is the foundation of all software and applications. It is the language that computers understand.
2. Machine code is the final form of a program that is executed by the CPU.
3. Machine code is specific to a particular computer architecture and is generated by compilers and assemblers.
4. Machine code is essential for the functioning of a computer system and is the basis of all software development.
5. Base Language:Har program (jaise MS Word, WhatsApp, games) last me machine code me convert hota hai, tabhi CPU usse execute karta hai.
6. Hardware Specific:Har processor ka apna machine code hota hai. Jo ek CPU ke liye kaam karega, zaruri nahi ki dusre ke liye bhi kare.


------------------------------------------------------------Conclusion---------------------------------------------------------------------------

1. Machine Code ek computer ki sabse basic language hai.
2. High-level languages ko machine code me convert karna padta hai, tabhi computer ka processor kaam kar pata hai.
3. Machine code binary format me hota hai, jo sirf 0 aur 1 me hota hai.
4. Machine code directly CPU ke liye samajhne me madad karta hai.
5. Machine code ke bina koi bhi software ya application execute nahi ho sakti.
6. Machine code is the backbone of all software development and computer operations.

*/